path_classifiers:
    test:
      - "tests/*"

extraction:
    cpp:
        configure:
            command:
                - export INSTALL_ROOT=/opt/out
                - export PKG_CONFIG_PATH=$INSTALL_ROOT/lib/pkgconfig:$PKG_CONFIG_PATH
                - bash -x ./scripts/build-libdivecomputer.sh
                - mkdir _lgtm_build_dir
                - cd _lgtm_build_dir
                - cmake -DLIBGIT2_DYNAMIC=ON -DCMAKE_VERBOSE_MAKEFILE=ON ..

queries:
    - exclude: "cpp/short-global-name"
