.TH subsurface 1 "Dec 15, 2013"
.SH NAME
subsurface \- a logbook program for scuba divers
.SH SYNOPSIS
.B subsurface
[options] [FILE...] [\-import] [FILE...]
.SH DESCRIPTION
.B subsurface
allows you to manage your dive logs that you can download from your dive computer or import from existing XML files.
.PP
You can click on the column headings to sort the dives based on this column.
.PP
Additional dives that get imported will be assigned numbers if they
don't already have numbers, are after all currently stored dives and
the last of those dives is numbered.
.PP
For full usage information see Subsurface User Manual, available on-line
at http://subsurface-divelog.org/ and locally under Help menu.
.SH OPTIONS
.B \-v
show more output during processing
.PP
.B \-\-import
all further files should be processed as import, not open
.PP
.B \-\-help
command line usage help
.PP
.B \-\-version
print Subsurface version information
.SH BUGS
If you find bugs, report at http://trac.subsurface-divelog.org
