.TH subsurface 1 2011/10/12
.SH NAME
subsurface
.SH SYNOPSIS
.B subsurface
[options] [FILE...] [-import] [FILE...]
.SH DESCRIPTION
.B subsurface
allows you to manage your dive logs that you can download from your dive computer or import from existing XML files.
.PP
The 
.B Dive Profile
and
.B Dive List
tabs can be ripped off from the notebook to create up to three independent windows.
.PP
You can click on the the column headings to sort the dives based on this column.
.PP
Additional dives that get imported will be assigned numbers if they
don't already have numbers, are after all currently stored dives and
the last of those dives is numbered.
.SH OPTIONS
.B -v
show more output during processing
.PP
.B --import
all further files should be processed as import, not open 
.SH BUGS
lots. Tell us if you find some.
