ARG VERSION

# Start from the container that we created in stage 1
From subsurface/mxe-build-container:$VERSION

# this time the settings include QtWebKit - since everything else was built
# during the first stage, QtWebKit will be the only thing that gets built
ADD settings-stage2.mk /win/mxe/settings.mk
RUN cd /win/mxe ; \
    make -j 2 2>&1 | tee build.log ;
RUN cd /win/mxe ; \
    make MXE_TARGETS=i686-w64-mingw32.static glib mdbtools -j 6 2>&1 | tee -a build.log ;

