if(NO_USERMANUAL)
	message(STATUS "building without usermanual")
	add_definitions(-DNO_USERMANUAL)
else()
		message(STATUS "building with QWebEngine")
		list(APPEND QT_EXTRA_COMPONENTS WebEngineWidgets)
endif()
