name: Android Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - scripts/docker/android-build-container/**
    - scripts/get-dep-lib.sh
    - .github/workflows/android-dockerimage.yml

jobs:
  android-build-container:
    runs-on: ubuntu-latest
    env:
      VERSION: 6.10.3-2 # the version number is based on the Qt version

    steps:
    - uses: actions/checkout@v6

    - name: Build the name for the docker image
      id: build_name
      run: |
        v=$VERSION
        b=$GITHUB_REF # -BRANCH suffix, unless the branch is master
        b=${b/refs\/heads\//}
        b=${b,,} # the name needs to be all lower case
        if [ $b = "master" ] ; then b="" ; else b="-$b" ; fi
        echo "NAME=$GITHUB_REPOSITORY_OWNER/android-build${b}:${v}" >> $GITHUB_OUTPUT

    - name: Copy content into place
      run: |
        # all files used by the docker build below need to be inside the workdir
        cp ./scripts/get-dep-lib.sh ./scripts/docker/android-build-container/

    - name: Build and Publish Linux Docker image to Dockerhub
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name:       ${{ steps.build_name.outputs.NAME }}
        username:   ${{ secrets.DOCKER_USERNAME }}
        password:   ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: 'Dockerfile'
        workdir:    './scripts/docker/android-build-container/'
