name: Documentation

on:
  push:
    paths-ignore:
    - scripts/docker/**
    branches:
    - master
  pull_request:
    paths-ignore:
    - scripts/docker/**
    branches:
    - master

jobs:
  documentation:
    runs-on: ubuntu-22.04

    steps:
    - name: install packages
      run: |
        sudo apt-get -y update
        sudo apt-get -y install asciidoc docbook-xml w3m

    - name: checkout sources
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: set the version information
      id: version_number
      uses: ./.github/actions/manage-version
      with:
        nightly-builds-secret: ${{ secrets.NIGHTLY_BUILDS }}

    - name: process the documentation
      working-directory: Documentation
      run: make

    - name: publish artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Subsurface-Documentation-${{ steps.version_number.outputs.version }}
        path: |
          Documentation/user-manual*.text
          Documentation/user-manual*.html
          Documentation/user-manual*.pdf
          Documentation/mobile-manual*.text
          Documentation/mobile-manual*.html
          Documentation/mobile-manual*.pdf
          Documentation/images/
          Documentation/mobile-images/
