name: Fedora Copr Build
on:
  push:
    paths-ignore:
    - scripts/docker/**
    branches:
    - master
    - current

jobs:
  setup-build:
    name: Submit build to Fedora COPR
    # this seems backwards, but we want to run under Fedora, but Github doesn' support that
    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    steps:
    - name: Setup build dependencies in the Fedora container
      run: |
        dnf -y install @development-tools @rpm-development-tools
        dnf -y install copr-cli make

    - name: Check out sources
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: setup git
      run: |
        git config --global --add safe.directory /__w/subsurface/subsurface
        git config --global --add safe.directory /__w/subsurface/subsurface/libdivecomputer

    - name: set the version information
      id: version_number
      uses: ./.github/actions/manage-version
      with:
        nightly-builds-secret: ${{ secrets.NIGHTLY_BUILDS }}

    - name: Setup API token for copr-cli
      env:
        API_TOKEN: ${{ secrets.COPR_TOKEN }}
        API_LOGIN: ${{ secrets.COPR_LOGIN }}
      run: |
        mkdir -p "$HOME/.config"
        cp packaging/copr/config.copr "$HOME/.config/copr"
        sed -i "s/API_TOKEN/$API_TOKEN/;s/API_LOGIN/$API_LOGIN/" "$HOME/.config/copr"

    - name: Checkout googlemaps
      run: |
        cd ..
        git clone https://github.com/subsurface/googlemaps

    - name: run the copr build script
      run: |
        cd ..
        bash -x subsurface/packaging/copr/make-package.sh $GITHUB_REF_NAME

