name: Ubuntu 22.04 / Qt 5

on:
  push:
    paths-ignore:
    - scripts/docker/**
    branches:
    - master
  pull_request:
    paths-ignore:
    - scripts/docker/**
    branches:
    - master
  workflow_dispatch:

jobs:
  do-build-test:
    uses: ./.github/workflows/linux-debian-generic.yml
    with:
      container-image: ubuntu:22.04
