name: Post Release Notes

on:
  push:
    paths-ignore:
    - scripts/docker/**
    branches:
    - master

jobs:
  postRelease:
    runs-on: ubuntu-latest
    steps:
    - name: checkout sources
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
        submodules: recursive

    - name: set the version information
      id: version_number
      uses: ./.github/actions/manage-version
      with:
        nightly-builds-secret: ${{ secrets.NIGHTLY_BUILDS }}

    # since we are running this step on a pull request, we will skip build numbers in releases
    - name: assemble release notes
      env:
        EVENT_HEAD_COMMIT_ID: ${{ github.event.head_commit.id }}
        # Required because we are using the GitHub CLI in 'create-releasenotes.sh'
        GH_TOKEN: ${{ github.token }}
      run: |
        scripts/create-releasenotes.sh $EVENT_HEAD_COMMIT_ID

    # add a file containing the release title so it can be picked up and listed on the release page on our web server
    - name: publish release
      if: github.event_name == 'push'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ steps.version_number.outputs.version }}
        repository: ${{ github.repository_owner }}/nightly-builds
        token: ${{ secrets.NIGHTLY_BUILDS }}
        prerelease: false
        files: release_content_title.txt
        body_path: gh_release_notes.md
