name: Windows (MXE) Docker Image

on:
  push:
    branches:
    - master
    paths:
    - scripts/docker/mxe-build-container/**
    - .github/workflows/windows-mxe-dockerimage.yml

jobs:
  windows-mxe:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ '3.4.0' }}    # 'official' images should have a dot-zero version
      # Fix this here as QTWebKit (needed for printing) is broken in newer versions
      mxe_sha: 'd6377b2f2334694dbb040294fd0d848327e63328'

    steps:
    - uses: actions/checkout@v4

    - name: Build the name for the docker image
      id: build_name
      run: |
        v=$VERSION
        b=$GITHUB_REF # -BRANCH suffix, unless the branch is master
        b=${b/refs\/heads\//}
        b=${b,,} # the name needs to be all lower case
        if [ $b = "master" ] ; then b="" ; else b="-$b" ; fi
        echo "NAME=$GITHUB_REPOSITORY_OWNER/mxe-build${b}:${v}" >> $GITHUB_OUTPUT

    - name: Build and Publish Linux Docker image to Dockerhub
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name:       ${{ steps.build_name.outputs.NAME }}
        username:   ${{ secrets.DOCKER_USERNAME }}
        password:   ${{ secrets.DOCKER_PASSWORD }}
        workdir:    './scripts/docker/mxe-build-container/'
        buildargs:  mxe_sha
